name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: "{{defaultContext}}:mysubdir"
                file: 02-kube-news/src/Dockerfile
                push: true
                tags: |
                  rycpyres/kube-news-maratona:v${{ github.run_number}}
                  rycpyres/kube-news-maratona:latest

    CD:
        needs: [CI]
        runs-on: ubuntu-latest
        
        steps:
            - run: echo "Obter o código"
            - run: echo "Configurar o Kubeconfig"
            - run: echo "Executar o apply"
